# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Huntsman' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Huntsman
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
pod "MBCircularProgressBar"
pod 'XLPagerTabStrip'
pod 'ActionSheetPicker-3.0', '~> 2.2'
pod 'NextGrowingTextView'
pod 'Firebase/Core'
pod 'Fabric'
pod 'Crashlytics'
pod 'Socket.IO-Client-Swift', '~> 11.1.3'
pod 'BRYXBanner'
end
